from typing import List, Dict, Any

from datetime import datetime, timezone

PROJECTS_DATA: List[Dict[str, Any]] = [
    {
        "id": "11111111-1111-1111-1111-111111111111",
        "title": "Virtual Pain Clinic (VPC)",
        "description": "A production-oriented healthcare platform that leverages Agentic AI to automate patient intake, clinical screening, and structured medical documentation with adaptive workflows and AI-generated summaries.",
        "long_description": "Built a production-oriented healthcare platform that leverages Agentic AI to automate patient intake, adaptive conversations, and structured documentation workflows using AWS Bedrock and LangGraph.",
        "tech_stack": ["Python", "FastAPI", "LangGraph", "AWS Bedrock", "React", "Three.js", "Docker"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507",
        "live_url": "",
        "category": "Healthcare AI",
        "featured": True,
        "order": 1,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "22222222-2222-2222-2222-222222222222",
        "title": "Hyundai AI Sales Assistant",
        "description": "A production-grade conversational AI assistant for the automotive industry that helps customers discover vehicles, compare variants, and receive recommendations using multi-agent workflows and structured retrieval.",
        "long_description": "Built a production-grade assistant for the automotive industry with LangGraph-driven workflows, retrieval-based reasoning, and contextual conversations.",
        "tech_stack": ["Python", "FastAPI", "LangGraph", "Ollama", "RAG", "Streamlit", "Snowflake"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/Hyundai-Sales-AI-Agent",
        "live_url": "",
        "category": "Automotive AI",
        "featured": True,
        "order": 2,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "33333333-3333-3333-3333-333333333333",
        "title": "Nexus AI",
        "description": "A modular enterprise AI platform for reusable LLM orchestration, RAG pipelines, document intelligence, embeddings, and prompt management.",
        "long_description": "Developed an enterprise AI platform featuring modular orchestration, prompt management, embeddings, and retrieval pipelines for document intelligence workflows.",
        "tech_stack": ["Python", "FastAPI", "LangChain", "ChromaDB", "FAISS", "RAG", "Docker"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/AIStudio",
        "live_url": "",
        "category": "Enterprise AI",
        "featured": True,
        "order": 3,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "44444444-4444-4444-4444-444444444444",
        "title": "SmartMergeAI",
        "description": "An AI-powered GitHub pull request review assistant that analyzes repositories, summarizes changes, and helps developers understand pull requests using Retrieval-Augmented Generation.",
        "long_description": "Built a developer-assistant tool that improves pull request understanding by combining repository analysis with semantic search and LLM summarization.",
        "tech_stack": ["Python", "FastAPI", "Ollama", "LangChain", "GitHub API", "RAG"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/SMI",
        "live_url": "",
        "category": "Developer AI",
        "featured": False,
        "order": 4,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "55555555-5555-5555-5555-555555555555",
        "title": "KnowledgeWeaver",
        "description": "An enterprise RAG chatbot capable of answering questions over organizational documents using semantic search, embeddings, and contextual retrieval.",
        "long_description": "Built a retrieval-first assistant for enterprise knowledge discovery and contextual document Q&A workflows.",
        "tech_stack": ["Python", "FastAPI", "RAG", "Embeddings", "LangChain"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/KnowledgeWeaver",
        "live_url": "",
        "category": "Knowledge AI",
        "featured": False,
        "order": 5,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "66666666-6666-6666-6666-666666666666",
        "title": "SmartDocs",
        "description": "An AI-powered document intelligence platform that extracts, indexes, and answers questions from uploaded PDFs and documents.",
        "long_description": "Developed an intelligent document workflow that combines extraction, indexing, and semantic retrieval for PDF-based knowledge access.",
        "tech_stack": ["Python", "FastAPI", "Ollama", "RAG", "Document AI"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/SmartDocs",
        "live_url": "",
        "category": "Document AI",
        "featured": False,
        "order": 6,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "77777777-7777-7777-7777-777777777777",
        "title": "LifeSaver AI",
        "description": "A healthcare-focused RAG application combining vector search, embeddings, and LLMs to deliver contextual medical knowledge.",
        "long_description": "Built a healthcare knowledge assistant for contextual medical information retrieval and grounded answer generation.",
        "tech_stack": ["Python", "FastAPI", "RAG", "Embeddings", "Healthcare AI"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507",
        "live_url": "",
        "category": "Healthcare AI",
        "featured": False,
        "order": 7,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
    {
        "id": "88888888-8888-8888-8888-888888888888",
        "title": "Nova Movie Recommendation Assistant",
        "description": "A conversational recommendation system that uses LLM reasoning to suggest movies based on user preferences.",
        "long_description": "Built a conversational recommendation assistant that combines preference understanding with LLM-based reasoning for movie suggestions.",
        "tech_stack": ["Python", "FastAPI", "LLM", "Recommendation AI"],
        "image_url": "",
        "github_url": "https://github.com/Venkatesh-ap-2507/Nova-Movie-Ticket-Booking",
        "live_url": "",
        "category": "Recommendation AI",
        "featured": False,
        "order": 8,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    },
]

SKILLS_DATA: List[Dict[str, Any]] = [
    {"id": "33333333-3333-3333-3333-333333333333", "name": "OpenAI GPT-4o", "category": "Generative AI",
        "proficiency": 96, "icon": "openai", "order": 1, "created_at": datetime.now(timezone.utc)},
    {"id": "44444444-4444-4444-4444-444444444444", "name": "AWS Bedrock", "category": "Generative AI",
        "proficiency": 95, "icon": "bedrock", "order": 2, "created_at": datetime.now(timezone.utc)},
    {"id": "55555555-5555-5555-5555-555555555555", "name": "Claude", "category": "Generative AI",
        "proficiency": 94, "icon": "claude", "order": 3, "created_at": datetime.now(timezone.utc)},
    {"id": "66666666-6666-6666-6666-666666666666", "name": "LangChain", "category": "Generative AI",
        "proficiency": 95, "icon": "langchain", "order": 4, "created_at": datetime.now(timezone.utc)},
    {"id": "77777777-7777-7777-7777-777777777777", "name": "LangGraph", "category": "Generative AI",
        "proficiency": 94, "icon": "langgraph", "order": 5, "created_at": datetime.now(timezone.utc)},
    {"id": "88888888-8888-8888-8888-888888888888", "name": "Prompt Engineering", "category": "Generative AI",
        "proficiency": 95, "icon": "prompt-engineering", "order": 6, "created_at": datetime.now(timezone.utc)},
    {"id": "99999999-9999-9999-9999-999999999999", "name": "Function Calling", "category": "Generative AI",
        "proficiency": 94, "icon": "function-calling", "order": 7, "created_at": datetime.now(timezone.utc)},
    {"id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", "name": "Tool Calling", "category": "Generative AI",
        "proficiency": 94, "icon": "tool-calling", "order": 8, "created_at": datetime.now(timezone.utc)},
    {"id": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb", "name": "RAG", "category": "Generative AI",
        "proficiency": 95, "icon": "rag", "order": 9, "created_at": datetime.now(timezone.utc)},
    {"id": "cccccccc-cccc-cccc-cccc-cccccccccccc", "name": "Multi-Agent Systems", "category": "Generative AI",
        "proficiency": 93, "icon": "multi-agent-systems", "order": 10, "created_at": datetime.now(timezone.utc)},
    {"id": "dddddddd-dddd-dddd-dddd-dddddddddddd", "name": "Python", "category": "Backend",
        "proficiency": 96, "icon": "python", "order": 11, "created_at": datetime.now(timezone.utc)},
    {"id": "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee", "name": "FastAPI", "category": "Backend",
        "proficiency": 95, "icon": "fastapi", "order": 12, "created_at": datetime.now(timezone.utc)},
    {"id": "ffffffff-ffff-ffff-ffff-ffffffffffff", "name": "Django", "category": "Backend",
        "proficiency": 90, "icon": "django", "order": 13, "created_at": datetime.now(timezone.utc)},
    {"id": "11111111-2222-3333-4444-555555555555", "name": "Flask", "category": "Backend",
        "proficiency": 88, "icon": "flask", "order": 14, "created_at": datetime.now(timezone.utc)},
    {"id": "22222222-3333-4444-5555-666666666666", "name": "REST APIs", "category": "Backend",
        "proficiency": 94, "icon": "rest-apis", "order": 15, "created_at": datetime.now(timezone.utc)},
    {"id": "33333333-4444-5555-6666-777777777777", "name": "PostgreSQL", "category": "Backend",
        "proficiency": 93, "icon": "postgresql", "order": 16, "created_at": datetime.now(timezone.utc)},
    {"id": "44444444-5555-6666-7777-888888888888", "name": "MySQL", "category": "Backend",
        "proficiency": 91, "icon": "mysql", "order": 17, "created_at": datetime.now(timezone.utc)},
    {"id": "55555555-6666-7777-8888-999999999999", "name": "SQLAlchemy", "category": "Backend",
        "proficiency": 92, "icon": "sqlalchemy", "order": 18, "created_at": datetime.now(timezone.utc)},
    {"id": "66666666-7777-8888-9999-aaaaaaaaaaaa", "name": "Pydantic", "category": "Backend",
        "proficiency": 93, "icon": "pydantic", "order": 19, "created_at": datetime.now(timezone.utc)},
    {"id": "77777777-8888-9999-aaaa-bbbbbbbbbbbb", "name": "JWT", "category": "Backend",
        "proficiency": 91, "icon": "jwt", "order": 20, "created_at": datetime.now(timezone.utc)},
    {"id": "88888888-9999-aaaa-bbbb-cccccccccccc", "name": "AWS EC2", "category": "Cloud",
        "proficiency": 90, "icon": "aws-ec2", "order": 21, "created_at": datetime.now(timezone.utc)},
    {"id": "99999999-aaaa-bbbb-cccc-dddddddddddd", "name": "Amazon S3", "category": "Cloud",
        "proficiency": 89, "icon": "amazon-s3", "order": 22, "created_at": datetime.now(timezone.utc)},
    {"id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "name": "Amazon ECS", "category": "Cloud",
        "proficiency": 88, "icon": "amazon-ecs", "order": 23, "created_at": datetime.now(timezone.utc)},
    {"id": "bbbbbbbb-cccc-dddd-eeee-ffffffffffff", "name": "Amazon RDS", "category": "Cloud",
        "proficiency": 88, "icon": "amazon-rds", "order": 24, "created_at": datetime.now(timezone.utc)},
    {"id": "cccccccc-dddd-eeee-ffff-111111111111", "name": "IAM", "category": "Cloud",
        "proficiency": 87, "icon": "iam", "order": 25, "created_at": datetime.now(timezone.utc)},
    {"id": "dddddddd-eeee-ffff-1111-222222222222", "name": "CloudWatch", "category": "Cloud",
        "proficiency": 86, "icon": "cloudwatch", "order": 26, "created_at": datetime.now(timezone.utc)},
    {"id": "eeeeeeee-ffff-1111-2222-333333333333", "name": "Docker", "category": "Cloud",
        "proficiency": 92, "icon": "docker", "order": 27, "created_at": datetime.now(timezone.utc)},
    {"id": "ffffffff-1111-2222-3333-444444444444", "name": "GitHub Actions", "category": "Cloud",
        "proficiency": 90, "icon": "github-actions", "order": 28, "created_at": datetime.now(timezone.utc)},
    {"id": "11111111-aaaa-bbbb-cccc-555555555555", "name": "FAISS", "category": "AI Infrastructure",
        "proficiency": 94, "icon": "faiss", "order": 29, "created_at": datetime.now(timezone.utc)},
    {"id": "22222222-bbbb-cccc-dddd-666666666666", "name": "ChromaDB", "category": "AI Infrastructure",
        "proficiency": 92, "icon": "chromadb", "order": 30, "created_at": datetime.now(timezone.utc)},
    {"id": "33333333-cccc-dddd-eeee-777777777777", "name": "Embeddings", "category": "AI Infrastructure",
        "proficiency": 95, "icon": "embeddings", "order": 31, "created_at": datetime.now(timezone.utc)},
    {"id": "44444444-dddd-eeee-ffff-888888888888", "name": "Semantic Search", "category": "AI Infrastructure",
        "proficiency": 94, "icon": "semantic-search", "order": 32, "created_at": datetime.now(timezone.utc)},
    {"id": "55555555-eeee-ffff-1111-999999999999", "name": "Vector Database", "category": "AI Infrastructure",
        "proficiency": 92, "icon": "vector-database", "order": 33, "created_at": datetime.now(timezone.utc)},
    {"id": "66666666-ffff-1111-2222-aaaaaaaaaaaa", "name": "Structured Output", "category": "AI Infrastructure",
        "proficiency": 91, "icon": "structured-output", "order": 34, "created_at": datetime.now(timezone.utc)},
    {"id": "77777777-1111-2222-3333-bbbbbbbbbbbb", "name": "LLM Guardrails", "category": "AI Infrastructure",
        "proficiency": 91, "icon": "llm-guardrails", "order": 35, "created_at": datetime.now(timezone.utc)},
    {"id": "88888888-2222-3333-4444-cccccccccccc", "name": "Hallucination Mitigation", "category": "AI Infrastructure",
        "proficiency": 90, "icon": "hallucination-mitigation", "order": 36, "created_at": datetime.now(timezone.utc)},
    {"id": "99999999-3333-4444-5555-dddddddddddd", "name": "React", "category": "Frontend",
        "proficiency": 86, "icon": "react", "order": 37, "created_at": datetime.now(timezone.utc)},
]

EXPERIENCES_DATA: List[Dict[str, Any]] = [
    {
        "id": "99999999-9999-9999-9999-999999999999",
        "company": "64 Squares LLC",
        "role": "AI Engineer (Generative AI)",
        "description": "Designing and deploying production-grade Generative AI applications for enterprise healthcare and automotive platforms, spanning LLM engineering, Agentic AI orchestration, RAG systems, FastAPI backend services, and cloud-native deployment.",
        "tech_used": ["Python", "FastAPI", "LangGraph", "LangChain", "AWS Bedrock", "OpenAI GPT-4o", "Claude", "RAG", "PostgreSQL", "Docker", "AWS"],
        "start_date": "October 2024",
        "end_date": "Present",
        "is_current": True,
        "location": "Pune, India",
        "highlights": [
            "Built production-grade Agentic AI systems for the Virtual Pain Clinic and Hyundai AI Sales Assistant.",
            "Developed multi-agent workflows using LangGraph and LangChain with AWS Bedrock and OpenAI GPT-4o integrations.",
            "Designed hybrid RAG pipelines, structured output validation, guardrails, and semantic retrieval workflows.",
            "Created scalable FastAPI microservices for conversational AI, document intelligence, and backend orchestration.",
        ],
        "order": 1,
        "created_at": datetime.now(timezone.utc),
    },
    {
        "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
        "company": "FirstBit Solutions",
        "role": "Python Full Stack Developer",
        "description": "Contributed to scalable web applications and backend services with a focus on maintainable APIs, authentication, and business-driven feature development.",
        "tech_used": ["Python", "Django", "REST APIs", "JWT", "PostgreSQL", "Git", "GitHub"],
        "start_date": "August 2023",
        "end_date": "May 2024",
        "is_current": False,
        "location": "Hybrid",
        "highlights": [
            "Developed REST APIs and backend modules for reliable web services and platform features.",
            "Implemented JWT authentication and contributed to a more structured and maintainable architecture.",
            "Collaborated on full-stack feature delivery with a strong emphasis on clean code and maintainability.",
        ],
        "order": 2,
        "created_at": datetime.now(timezone.utc),
    },
]

CERTIFICATIONS_DATA: List[Dict[str, Any]] = [
    {
        "id": "11111111-2222-3333-4444-555555555555",
        "title": "Databricks Certified Generative AI Engineer Associate",
        "issuer": "Databricks",
        "year": "2025",
        "file_path": "Databricks Ceretified Generative AI Engineer Associate.JPG",
        "order": 1,
        "created_at": datetime.now(timezone.utc),
    },
    {
        "id": "22222222-3333-4444-5555-666666666666",
        "title": "Microsoft Certified: Azure AI Apps and Agents Developer Associate",
        "issuer": "Microsoft",
        "year": "2025",
        "file_path": "Microsoft Certified  Azure AI Apps  and Agents Developer Associate.JPG",
        "order": 2,
        "created_at": datetime.now(timezone.utc),
    },
    {
        "id": "33333333-4444-5555-6666-777777777777",
        "title": "Python Full Stack Developer",
        "issuer": "FirstBitSolution",
        "year": "2024",
        "file_path": "Python Full Stack Developer.pdf",
        "order": 3,
        "created_at": datetime.now(timezone.utc),
    },
]
